### ISSUE TITLE
Page for adding a new Experience

### ISSUE THREAD

**Issue by MLHProgram** [MLH-Fellowship/orientation-project-js-24.FAL.A#11]
Add a page that allows users to add a new Experience which includes the following fields:

- title
- company
- start_date
- end_date
- description
- logo

Collaborate with the fellows contributing to the Python project to understand how logos will be managed. For now, assume this is a string (URL to the image). 

When this information is submitted, a POST request should be made to `/resume/experience` on the server in the following format:

```json
{
    "title": "Software Developer",
    "company": "A Cooler Company",
    "start_date": "October 2022",    
    "end_date": "Present",
    "description": "Writing JavaScript Code",
    "logo": "example-logo.png",
}
```

The server will return a JSON with the position in the list in the following format:
```json
{
"id": 1
}
```

**Comment by larrytamnjong** [comment]
I would like to take on this issue.

**Comment by dannyl1u** [comment]
Note: the backend implementation for this feature only requires the `start_date` and `end_date` be a string, thus no specific format is needed :)

See https://github.com/MLH-Fellowship/orientation-project-python-24.FAL.A/pull/40#discussion_r1769018883
