### ISSUE TITLE
Export Resume as PDF

### ISSUE THREAD

**Issue by MLHProgram** [MLH-Fellowship/orientation-project-js-24.FAL.A#12]
Once a user has added all their information to the resume, they are able to export as a PDF. PDF must not crop off any information for the resume, but not include UI elements from the web page.

**Comment by davidkurilla** [comment]
I would like to try tackling this issue if its still open. I want to learn more react so I think this issue might be a good experience for me.

**Comment by sammychinedu2ky** [comment]
I will work on this
